service: slanj-api

frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  stage: dev
  architecture: arm64
  runtime: ${param:runtime, 'provided.al2'} 
  deploymentMethod: direct
  region: eu-central-1
  environment: 
    AWS_SDK_LOAD_CONFIG: true
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameter
      Resource: "*"

package:
  individually: true
  exclude:
    - ./src/**
  include:
    - ./.bin/**

plugins:
  - serverless-offline
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true
    monorepo: true
    cmd: GOOS=linux GOARCH=arm64 go build -ldflags="-s -w"

functions:
  health:
    handler: ./src/functions/health/main.go
    timeout: 30
    events:
      - http:
          path: /health
          method: get
  scores:
    handler: ./src/functions/get-scores/main.go
    timeout: 30
    events:
      - http:
          path: /scores
          method: get
  scores-add:
    handler: ./src/functions/add-score/main.go
    timeout: 30
    events:
      - http:
          path: /scores
          method: post
